"""Seed approved remediation_catalog entries for MVP + Phase 9A task codes.

Security:
- Playbook paths come only from this catalog (never Excel Remediation text,
  never AI generated_playbook).
- Phase 9A entries are enabled for local MVP/mock generate-plan coverage.
  Real Ansible still requires MOCK_MODE=false, REAL_ANSIBLE_ENABLED=true,
  APP_ENV=lab|test, and target environment gates (unchanged defaults).
- Older Phase 1 stub playbooks (except SSH_DISABLE_ROOT_LOGIN) remain disabled
  until individually reviewed.
"""

from sqlalchemy.orm import Session

from app.models.remediation_catalog import RemediationCatalog

# Playbook paths are relative to ANSIBLE_PLAYBOOKS_DIR.
MVP_CATALOG: list[dict[str, object]] = [
    {
        "task_code": "SSH_DISABLE_ROOT_LOGIN",
        "title": "Disable SSH root login (PermitRootLogin no)",
        "supported_os": "linux",
        "ansible_playbook_path": "ssh_disable_root_login.yml",
        "risk_level": "high",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": "sshd -t",
        "service_reload": "sshd",
        # Reviewed playbook — enabled.
        "is_enabled": True,
    },
    {
        "task_code": "SSH_DISABLE_X11_FORWARDING",
        "title": "Disable SSH X11 forwarding",
        "supported_os": "linux",
        "ansible_playbook_path": "ssh_disable_x11_forwarding.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": "sshd -t",
        "service_reload": "sshd",
        "is_enabled": False,  # stub playbook — disabled
    },
    {
        "task_code": "SSH_SET_MAX_SESSIONS",
        "title": "Set SSH MaxSessions",
        "supported_os": "linux",
        "ansible_playbook_path": "ssh_set_max_sessions.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": "sshd -t",
        "service_reload": "sshd",
        "is_enabled": False,  # stub playbook — disabled
    },
    {
        "task_code": "SET_PASS_MAX_DAYS",
        "title": "Set PASS_MAX_DAYS",
        "supported_os": "linux",
        "ansible_playbook_path": "set_pass_max_days.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": False,  # stub playbook — disabled
    },
    {
        "task_code": "SET_VAR_LOG_PERMISSIONS",
        "title": "Set /var/log permissions",
        "supported_os": "linux",
        "ansible_playbook_path": "set_var_log_permissions.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": False,  # stub playbook — disabled
    },
    {
        "task_code": "SET_TMP_NODEV",
        "title": "Mount /tmp with nodev",
        "supported_os": "linux",
        "ansible_playbook_path": "set_tmp_nodev.yml",
        "risk_level": "high",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": False,  # stub playbook — disabled
    },
    {
        "task_code": "SET_TMP_NOEXEC",
        "title": "Mount /tmp with noexec",
        "supported_os": "linux",
        "ansible_playbook_path": "set_tmp_noexec.yml",
        "risk_level": "high",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": False,  # stub playbook — disabled
    },
    {
        "task_code": "SET_DEV_SHM_NODEV",
        "title": "Mount /dev/shm with nodev",
        "supported_os": "linux",
        "ansible_playbook_path": "set_dev_shm_nodev.yml",
        "risk_level": "high",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": False,  # stub playbook — disabled
    },
    {
        "task_code": "SET_DEV_SHM_NOEXEC",
        "title": "Mount /dev/shm with noexec",
        "supported_os": "linux",
        "ansible_playbook_path": "set_dev_shm_noexec.yml",
        "risk_level": "high",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": False,  # stub playbook — disabled
    },
    {
        "task_code": "SET_SELINUX_MODE",
        "title": "Set SELinux mode",
        "supported_os": "linux",
        "ansible_playbook_path": "set_selinux_mode.yml",
        "risk_level": "critical",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": False,  # stub playbook — disabled
    },
    {
        "task_code": "SET_MOTD_BANNER",
        "title": "Set /etc/motd banner",
        "supported_os": "linux",
        "ansible_playbook_path": "set_motd_banner.yml",
        "risk_level": "low",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": False,  # stub playbook — disabled
    },
    {
        "task_code": "SET_SSH_LOGIN_BANNER",
        "title": "Set SSH login banner",
        "supported_os": "linux",
        "ansible_playbook_path": "set_ssh_login_banner.yml",
        "risk_level": "low",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": "sshd -t",
        "service_reload": "sshd",
        "is_enabled": False,  # stub playbook — disabled
    },
    # --- Phase 9A top Qualys coverage (enabled for MVP/mock plan generation) ---
    {
        "task_code": "PASSWORD_MIN_AGE",
        "title": "Set PASS_MIN_DAYS to 1",
        "supported_os": "linux",
        "ansible_playbook_path": "password_min_age.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": True,
    },
    {
        "task_code": "SYSCTL_IPV4_SECURE_REDIRECTS_DISABLE",
        "title": "Disable IPv4 secure redirects (net.ipv4.conf.all.secure_redirects=0)",
        "supported_os": "linux",
        "ansible_playbook_path": "sysctl_ipv4_secure_redirects_disable.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": True,
    },
    {
        "task_code": "SYSCTL_IPV6_ACCEPT_RA_DISABLE",
        "title": "Disable IPv6 accept_ra (net.ipv6.conf.default.accept_ra=0)",
        "supported_os": "linux",
        "ansible_playbook_path": "sysctl_ipv6_accept_ra_disable.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": True,
    },
    {
        "task_code": "JOURNALD_COMPRESS_ENABLE",
        "title": "Enable journald Compress=yes",
        "supported_os": "linux",
        "ansible_playbook_path": "journald_compress_enable.yml",
        "risk_level": "low",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": True,
    },
    {
        "task_code": "SSH_IGNORE_RHOSTS_ENABLE",
        "title": "Enable SSH IgnoreRhosts yes",
        "supported_os": "linux",
        "ansible_playbook_path": "ssh_ignore_rhosts_enable.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": "sshd -t",
        "service_reload": "sshd",
        "is_enabled": True,
    },
    {
        "task_code": "SSH_LOG_LEVEL_INFO",
        "title": "Set SSH LogLevel INFO",
        "supported_os": "linux",
        "ansible_playbook_path": "ssh_log_level_info.yml",
        "risk_level": "low",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": "sshd -t",
        "service_reload": "sshd",
        "is_enabled": True,
    },
    {
        "task_code": "SSH_MAX_AUTH_TRIES",
        "title": "Set SSH MaxAuthTries 4 (or stricter)",
        "supported_os": "linux",
        "ansible_playbook_path": "ssh_max_auth_tries.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": "sshd -t",
        "service_reload": "sshd",
        "is_enabled": True,
    },
    {
        "task_code": "SSH_CLIENT_ALIVE_INTERVAL",
        "title": "Set SSH ClientAliveInterval 300",
        "supported_os": "linux",
        "ansible_playbook_path": "ssh_client_alive_interval.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": "sshd -t",
        "service_reload": "sshd",
        "is_enabled": True,
    },
    {
        "task_code": "SHELL_TMOUT",
        "title": "Set shell TMOUT=600",
        "supported_os": "linux",
        "ansible_playbook_path": "shell_tmout.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": True,
    },
    {
        "task_code": "CRONTAB_PERMISSIONS",
        "title": "Set /etc/crontab permissions to 600",
        "supported_os": "linux",
        "ansible_playbook_path": "crontab_permissions.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": True,
    },
    {
        "task_code": "CRON_DAILY_PERMISSIONS",
        "title": "Set /etc/cron.daily permissions to 700",
        "supported_os": "linux",
        "ansible_playbook_path": "cron_daily_permissions.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": True,
    },
    {
        "task_code": "CRON_HOURLY_PERMISSIONS",
        "title": "Set /etc/cron.hourly permissions to 700",
        "supported_os": "linux",
        "ansible_playbook_path": "cron_hourly_permissions.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": True,
    },
    {
        "task_code": "CRON_WEEKLY_PERMISSIONS",
        "title": "Set /etc/cron.weekly permissions to 700",
        "supported_os": "linux",
        "ansible_playbook_path": "cron_weekly_permissions.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": True,
    },
    {
        "task_code": "CRON_MONTHLY_PERMISSIONS",
        "title": "Set /etc/cron.monthly permissions to 700",
        "supported_os": "linux",
        "ansible_playbook_path": "cron_monthly_permissions.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": True,
    },
    {
        "task_code": "RSYNC_REMOVE",
        "title": "Remove rsync package",
        "supported_os": "linux",
        "ansible_playbook_path": "rsync_remove.yml",
        "risk_level": "high",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": True,
    },
    {
        "task_code": "X11_SERVER_REMOVE",
        "title": "Remove xorg-x11-server packages",
        "supported_os": "linux",
        "ansible_playbook_path": "x11_server_remove.yml",
        "risk_level": "high",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": True,
    },
    {
        "task_code": "AIDE_INSTALL",
        "title": "Install aide package",
        "supported_os": "linux",
        "ansible_playbook_path": "aide_install.yml",
        "risk_level": "medium",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": True,
    },
    {
        "task_code": "HOME_PARTITION_NODEV",
        "title": "Ensure /home fstab entry has nodev",
        "supported_os": "linux",
        "ansible_playbook_path": "home_partition_nodev.yml",
        "risk_level": "high",
        "requires_approval": True,
        "requires_dry_run": True,
        "requires_backup": True,
        "requires_validation": True,
        "validation_command": None,
        "service_reload": None,
        "is_enabled": True,
    },
]

# Phase 9A task codes expected in seed (for tests / docs).
PHASE9A_TASK_CODES: frozenset[str] = frozenset(
    {
        "PASSWORD_MIN_AGE",
        "SYSCTL_IPV4_SECURE_REDIRECTS_DISABLE",
        "SYSCTL_IPV6_ACCEPT_RA_DISABLE",
        "JOURNALD_COMPRESS_ENABLE",
        "SSH_IGNORE_RHOSTS_ENABLE",
        "SSH_LOG_LEVEL_INFO",
        "SSH_MAX_AUTH_TRIES",
        "SSH_CLIENT_ALIVE_INTERVAL",
        "SHELL_TMOUT",
        "CRONTAB_PERMISSIONS",
        "CRON_DAILY_PERMISSIONS",
        "CRON_HOURLY_PERMISSIONS",
        "CRON_WEEKLY_PERMISSIONS",
        "CRON_MONTHLY_PERMISSIONS",
        "RSYNC_REMOVE",
        "X11_SERVER_REMOVE",
        "AIDE_INSTALL",
        "HOME_PARTITION_NODEV",
    }
)


def seed_remediation_catalog(db: Session) -> int:
    """Insert missing catalog rows and enforce enabled flags from seed.

    Returns number of inserted or updated rows.
    """
    changed = 0
    for item in MVP_CATALOG:
        existing = (
            db.query(RemediationCatalog)
            .filter(RemediationCatalog.task_code == item["task_code"])
            .first()
        )
        if existing is None:
            db.add(RemediationCatalog(**item))  # type: ignore[arg-type]
            changed += 1
            continue

        # Keep seed authoritative for is_enabled and playbook path.
        desired_enabled = bool(item["is_enabled"])
        if existing.is_enabled != desired_enabled:
            existing.is_enabled = desired_enabled
            changed += 1
        if existing.ansible_playbook_path != item["ansible_playbook_path"]:
            existing.ansible_playbook_path = str(item["ansible_playbook_path"])
            changed += 1

    db.commit()
    return changed
