"""Approved remediation task codes for MVP.

Execution is allowed only for codes present in remediation_catalog
(except NEEDS_REVIEW / UNSUPPORTED_CONTROL which never execute).
"""

from enum import StrEnum


class TaskCode(StrEnum):
    SSH_DISABLE_ROOT_LOGIN = "SSH_DISABLE_ROOT_LOGIN"
    SSH_DISABLE_X11_FORWARDING = "SSH_DISABLE_X11_FORWARDING"
    SSH_SET_MAX_SESSIONS = "SSH_SET_MAX_SESSIONS"
    SET_PASS_MAX_DAYS = "SET_PASS_MAX_DAYS"
    SET_VAR_LOG_PERMISSIONS = "SET_VAR_LOG_PERMISSIONS"
    SET_TMP_NODEV = "SET_TMP_NODEV"
    SET_TMP_NOEXEC = "SET_TMP_NOEXEC"
    SET_DEV_SHM_NODEV = "SET_DEV_SHM_NODEV"
    SET_DEV_SHM_NOEXEC = "SET_DEV_SHM_NOEXEC"
    SET_SELINUX_MODE = "SET_SELINUX_MODE"
    SET_MOTD_BANNER = "SET_MOTD_BANNER"
    SET_SSH_LOGIN_BANNER = "SET_SSH_LOGIN_BANNER"
    # Phase 9A — top Qualys coverage expansion
    PASSWORD_MIN_AGE = "PASSWORD_MIN_AGE"
    SYSCTL_IPV4_SECURE_REDIRECTS_DISABLE = "SYSCTL_IPV4_SECURE_REDIRECTS_DISABLE"
    SYSCTL_IPV6_ACCEPT_RA_DISABLE = "SYSCTL_IPV6_ACCEPT_RA_DISABLE"
    JOURNALD_COMPRESS_ENABLE = "JOURNALD_COMPRESS_ENABLE"
    SSH_IGNORE_RHOSTS_ENABLE = "SSH_IGNORE_RHOSTS_ENABLE"
    SSH_LOG_LEVEL_INFO = "SSH_LOG_LEVEL_INFO"
    SSH_MAX_AUTH_TRIES = "SSH_MAX_AUTH_TRIES"
    SSH_CLIENT_ALIVE_INTERVAL = "SSH_CLIENT_ALIVE_INTERVAL"
    SHELL_TMOUT = "SHELL_TMOUT"
    CRONTAB_PERMISSIONS = "CRONTAB_PERMISSIONS"
    CRON_DAILY_PERMISSIONS = "CRON_DAILY_PERMISSIONS"
    CRON_HOURLY_PERMISSIONS = "CRON_HOURLY_PERMISSIONS"
    CRON_WEEKLY_PERMISSIONS = "CRON_WEEKLY_PERMISSIONS"
    CRON_MONTHLY_PERMISSIONS = "CRON_MONTHLY_PERMISSIONS"
    RSYNC_REMOVE = "RSYNC_REMOVE"
    X11_SERVER_REMOVE = "X11_SERVER_REMOVE"
    AIDE_INSTALL = "AIDE_INSTALL"
    HOME_PARTITION_NODEV = "HOME_PARTITION_NODEV"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    UNSUPPORTED_CONTROL = "UNSUPPORTED_CONTROL"


# Codes that must never be executed by Ansible Runner.
NON_EXECUTABLE_TASK_CODES: frozenset[str] = frozenset(
    {
        TaskCode.NEEDS_REVIEW.value,
        TaskCode.UNSUPPORTED_CONTROL.value,
    }
)
